/*

INICIO
NUM_01 =NUMERO_RECEBIDO_DO_USUARIO
SORTE = NUMERO_RANDOMICO

SE NUM_01 == SORTE
    RETORNA PARABÉNS
SENÃO
    SE SORTE > NUM_01
        SORTE É MAIOR QUE O NUM_01

        NUM_2 = NUMERO_RECEBIDO_DO_USUARIO

        SE NUM_02 == SORTE
            PARABÉNS
        SENÃO
            
    SENÃO
        SORTE É MENOR QUE O NUM_01

        NUM_2 = NUMERO_RECEBIDO_DO_USUARIO

        SE NUM_02 == SORTE



*/